# Each array includes alternate names for each system.
# You can add your own systems and/or alternate names.
# If the first value is "Advanced", then it will only show up when "Show Advanced Systems" is enabled.
# Capitalization doesn't matter, and each name is already checked with and without " - " where applicable (for example, "Nokia - N-Gage" covers both "Nokia - N-Gage" and "Nokia N-Gage")

systemNamesDict = {
	"Acorn - Archimedes"                                           : ("Advanced",     ["Archimedes"]),
	"Acorn - Atom"                                                 : ("Advanced",     ["Atom"]),
	"Acorn - BBC Micro"                                            : ("Advanced",     ["bbcmicro", "BBC Micro"]),
	"ACT - Apricot PC Xi"                                          : ("Advanced",     ["Apricot PC Xi"]),
	"APF - Imagination Machine"                                    : ("Advanced",     ["Imagination Machine"]),
	"APF - MP-1000"                                                : ("Advanced",     ["MP-1000"]),
	"Apple - I"                                                    : ("Advanced",     ["apple1"]),
	"Apple - II"                                                   : ("Advanced",     ["apple2"]),
	"Apple - II Plus"                                              : ("Advanced",     ["apple2plus"]),
	"Apple - IIe"                                                  : ("Advanced",     ["apple2e"]),
	"Apple - IIGS"                                                 : ("Advanced",     ["apple2gs"]),
	"Apple - Macintosh"                                            : ("Advanced",     ["Macintosh"]),
	"Atari - 2600"                                                 : ("        ",     ["atari2600", "Atari - Atari 2600", "a2600"]),
	"Atari - 5200"                                                 : ("        ",     ["atari5200", "Atari - Atari 5200"]),
	"Atari - 7800"                                                 : ("        ",     ["atari7800"]),
	"Atari - 8-bit Family"                                         : ("Advanced",     ["atari800", "Atari - 800"]),
	"Atari - Jaguar"                                               : ("        ",     ["Jaguar"]),
	"Atari - Lynx"                                                 : ("        ",     ["lynx"]),
	"Atari - ST"                                                   : ("Advanced",     ["atarist", "Atari - Atari ST"]),
	"Atari - ST (Tapes)"                                           : ("Advanced",     ["Atari - Atari ST (Tapes)"]),
	"Bally - Astrocade"                                            : ("Advanced",     ["Astrocade"]),
	"Bally - Astrocade (Tapes)"                                    : ("Advanced",     ["Astrocade (Tapes)"]),
	"Bandai - Design Master Denshi Mangajuku"                      : ("Advanced",     ["Design Master Denshi Mangajuku"]),
	"Bandai - Gundam RX-78"                                        : ("Advanced",     ["Gundam RX-78"]),
	"Bandai - WonderSwan"                                          : ("        ",     ["wswan", "WonderSwan"]),
	"Bandai - WonderSwan Color"                                    : ("        ",     ["wswanc", "WonderSwan Color"]),
	"Benesse - Pocket Challenge V2"                                : ("Advanced",     ["Pocket Challenge V2"]),
	"Benesse - Pocket Challenge W"                                 : ("Advanced",     ["Pocket Challenge W"]),
	"Bit Corporation - Gamate"                                     : ("Advanced",     ["Gamate"]),
	"Casio - Loopy"                                                : ("Advanced",     ["Loopy"]),
	"Casio - PV-1000"                                              : ("Advanced",     ["PV-1000"]),
	"Coleco - ColecoVision"                                        : ("        ",     ["colecovision"]),
	"Commodore - Amiga"                                            : ("        ",     ["Amiga"]),
	"Commodore - Commodore 64"                                     : ("        ",     ["c64", "Commodore 64"]),
	"Commodore - Commodore 64 (PP)"                                : ("Advanced",     ["Commodore 64 (PP)"]),
	"Commodore - Commodore 64 (Tapes)"                             : ("Advanced",     ["Commodore 64 (Tapes)"]),
	"Commodore - Plus-4"                                           : ("Advanced",     []),
	"Commodore - VIC-20"                                           : ("Advanced",     ["vic20", "VIC-20", "Commodore - VIC20"]),
	"Emerson - Arcadia 2001"                                       : ("Advanced",     ["Arcadia 2001"]),
	"Entex - Adventure Vision"                                     : ("Advanced",     ["Adventure Vision"]),
	"Epoch - Game Pocket Computer"                                 : ("Advanced",     ["Game Pocket Computer"]),
	"Epoch - Super Cassette Vision"                                : ("Advanced",     ["Super Cassette Vision"]),
	"Fairchild - Channel F"                                        : ("Advanced",     ["channelf", "Channel F"]),
	"Fukutake Publishing - StudyBox"                               : ("Advanced",     ["StudyBox"]),
	"Funtech - Super Acan"                                         : ("Advanced",     ["Super Acan"]),
	"GamePark - GP2X"                                              : ("Advanced",     ["GP2X"]),
	"GamePark - GP2X (Digital)"                                    : ("Advanced",     ["GP2X (Digital)"]),
	"GamePark - GP32"                                              : ("Advanced",     ["GP32"]),
	"GCE - Vectrex"                                                : ("        ",     ["vectrex"]),
	"Google - Android (Misc)"                                      : ("Advanced",     ["Android (Misc)"]),
	"Hartung - Game Master"                                        : ("Advanced",     ["Game Master"]),
	"IBM - PC and Compatibles"                                     : ("Advanced",     []),
	"IBM - PC and Compatibles (Digital) (Desura)"                  : ("Advanced",     []),
	"IBM - PC and Compatibles (Digital) (Misc)"                    : ("Advanced",     []),
	"IBM - PC and Compatibles (Digital) (Misc) (Adult)"            : ("Advanced",     []),
	"IBM - PC and Compatibles (Digital) (Unknown)"                 : ("Advanced",     []),
	"Interton - VC 4000"                                           : ("Advanced",     ["VC 4000"]),
	"iQue - iQue"                                                  : ("Advanced",     ["iQue"]),
	"Konami - Picno"                                               : ("Advanced",     ["Picno"]),
	"LeapFrog - LeapPad"                                           : ("Advanced",     ["LeapPad"]),
	"LeapFrog - Leapster Learning Game System"                     : ("Advanced",     ["Leapster Learning Game System"]),
	"LeapFrog - My First LeapPad"                                  : ("Advanced",     ["My First LeapPad"]),
	"Magnavox - Odyssey2"                                          : ("Advanced",     ["Odyssey2", "Magnavox - Odyssey 2"]),
	"Mattel - Intellivision"                                       : ("        ",     ["intellivision"]),
	"Microsoft - MSX"                                              : ("        ",     ["msx1", "MSX"]),
	"Microsoft - MSX2"                                             : ("        ",     ["msx2"]),
	"Microsoft - XBOX 360 (Digital)"                               : ("Advanced",     ["XBOX 360 (Digital)"]),
	"Mobile - J2ME"                                                : ("Advanced",     ["J2ME"]),
	"Mobile - Palm OS"                                             : ("Advanced",     ["palm", "Palm OS"]),
	"Mobile - Symbian"                                             : ("Advanced",     ["Symbian"]),
	"NEC - PC Engine - TurboGrafx 16"                              : ("        ",     ["pcengine", "tg16", "PC Engine - TurboGrafx 16", "NEC - PC Engine", "PC Engine", "NEC - TurboGrafx 16", "TurboGrafx 16", "NEC - TurboGrafx16", "TurboGrafx16"]),
	"NEC - PC Engine SuperGrafx"                                   : ("Advanced",     ["supergrafx", "PC Engine SuperGrafx"]),
	"Nichibutsu - My Vision"                                       : ("Advanced",     ["My Vision"]),
	"Nintendo - amiibo"                                            : ("Advanced",     ["amiibo"]),
	"Nintendo - e-Reader"                                          : ("Advanced",     ["e-Reader"]),
	"Nintendo - Family Computer Disk System"                       : ("        ",     ["fds", "Family Computer Disk System", "Nintendo - Famicom Disk System", "Famicom Disk System"]),
	"Nintendo - Family Computer Network System"                    : ("Advanced",     ["Family Computer Network System"]),
	"Nintendo - Game & Watch"                                      : ("        ",     ["gw", "Nintendo - Game &amp; Watch", "Game &amp; Watch", "Game & Watch"]),
	"Nintendo - Game Boy"                                          : ("        ",     ["gb", "Game Boy", "Gameboy"]),
	"Nintendo - Game Boy Advance"                                  : ("        ",     ["gba", "Game Boy Advance", "Gameboy Advance", "Nintendo - Gameboy Advance"]),
	"Nintendo - Game Boy Advance (Multiboot)"                      : ("        ",     ["Game Boy Advance (Multiboot)"]),
	"Nintendo - Game Boy Color"                                    : ("        ",     ["gbc", "Game Boy Color", "Gameboy Color", "Nintendo - Gameboy Color"]),
	"Nintendo - Kiosk Video Compact Flash"                         : ("Advanced",     ["Kiosk Video Compact Flash"]),
	"Nintendo - Mario no Photopi SmartMedia"                       : ("Advanced",     ["Mario no Photopi SmartMedia"]),
	"Nintendo - Misc"                                              : ("Advanced",     []),
	"Nintendo - New Nintendo 3DS"                                  : ("Advanced",     ["New Nintendo 3DS", "New 3DS"]),
	"Nintendo - New Nintendo 3DS (Digital)"                        : ("Advanced",     ["New Nintendo 3DS (Digital)"]),
	"Nintendo - Nintendo 3DS"                                      : ("Advanced",     ["Nintendo 3DS", "3DS"]),
	"Nintendo - Nintendo 3DS (Digital)"                            : ("Advanced",     ["Nintendo 3DS (Digital)", "3DS (Digital)"]),
	"Nintendo - Nintendo 3DS (Digital) (CDN)"                      : ("Advanced",     ["Nintendo 3DS (Digital) (CDN", "3DS (Digital) (CDN"]),
	"Nintendo - Nintendo 64"                                       : ("        ",     ["n64", "Nintendo 64"]),
	"Nintendo - Nintendo 64DD"                                     : ("        ",     ["64dd", "Nintendo 64DD"]),
	"Nintendo - Nintendo DS"                                       : ("        ",     ["ds", "nds", "Nintendo DS"]),
	"Nintendo - Nintendo DS (Download Play)"                       : ("        ",     ["Nintendo DS (Download Play)"]),
	"Nintendo - Nintendo DSi"                                      : ("Advanced",     ["Nintendo DSi", "DSi"]),
	"Nintendo - Nintendo DSi (Digital)"                            : ("Advanced",     ["Nintendo DSi (Digital)"]),
	"Nintendo - Nintendo DSi (Digital) (CDN)"                      : ("Advanced",     ["Nintendo DSi (Digital) (CDN)"]),
	"Nintendo - Nintendo Entertainment System"                     : ("        ",     ["nes", "Nintendo Entertainment System", "Nintendo - Famicom", "Famicom"]),
	"Nintendo - Play-Yan"                                          : ("Advanced",     ["Play-Yan"]),
	"Nintendo - Pokemon Mini"                                      : ("        ",     ["pokemini", "Pokemon Mini"]),
	"Nintendo - Satellaview"                                       : ("        ",     ["satellaview"]),
	"Nintendo - Sufami Turbo"                                      : ("Advanced",     ["sufami", "Sufami Turbo"]),
	"Nintendo - Super Nintendo Entertainment System"               : ("        ",     ["snes", "Super Nintendo Entertainment System", "Super Nintendo", "Nintendo - Super Famicom", "Super Famicom"]),
	"Nintendo - Virtual Boy"                                       : ("        ",     ["virtualboy", "Virtual Boy"]),
	"Nintendo - Wii (Digital) (CDN)"                               : ("Advanced",     ["Wii (Digital) (CDN)"]),
	"Nintendo - Wii U (Digital) (CDN)"                             : ("Advanced",     ["Wii U (Digital) (CDN)"]),
	"Nokia - N-Gage"                                               : ("Advanced",     ["N-Gage"]),
	"Nokia - N-Gage 2.0"                                           : ("Advanced",     ["N-Gage 2.0"]),
	"Ouya - Ouya"                                                  : ("Advanced",     ["Ouya"]),
	"Philips - Videopac+"                                          : ("Advanced",     ["videopacplus", "Videopac+"]),
	"RCA - Studio II"                                              : ("Advanced",     ["Studio II"]),
	"Sega - 32X"                                                   : ("        ",     ["sega32x", "32X"]),
	"Sega - Beena"                                                 : ("Advanced",     ["Beena"]),
	"Sega - Game Gear"                                             : ("        ",     ["gamegear", "Game Gear"]),
	"Sega - Master System - Mark III"                              : ("        ",     ["mastersystem", "Master System - Mark III", "Sega - Master System", "Master System", "SMS"]),
	"Sega - Mega Drive - Genesis"                                  : ("        ",     ["megadrive", "Sega Genesis", "Genesis", "Sega Mega Drive", "Mega Drive"]),
	"Sega - PICO"                                                  : ("Advanced",     ["PICO"]),
	"Sega - SG-1000"                                               : ("        ",     ["sg1000", "SG-1000"]),
	"Seta - Aleck64"                                               : ("Advanced",     ["Aleck64"]),
	"Sinclair - ZX Spectrum +3"                                    : ("        ",     ["zxspectrum", "ZX Spectrum +3", "ZX Spectrum"]),
	"SNK - Neo Geo Pocket"                                         : ("        ",     ["ngp", "Neo Geo Pocket"]),
	"SNK - Neo Geo Pocket Color"                                   : ("        ",     ["ngpc", "Neo Geo Pocket Color"]),
	"Sony - PlayStation (PS one Classics) (PSN)"                   : ("Advanced",     ["PlayStation (PS one Classics) (PSN)"]),
	"Sony - PlayStation 3 (PSN) (Content)"                         : ("Advanced",     ["PlayStation 3 (PSN) (Content)"]),
	"Sony - PlayStation Mobile (PSN)"                              : ("Advanced",     ["PlayStation Mobile (PSN)"]),
	"Sony - PlayStation Portable (PSN) (Encrypted)"                : ("Advanced",     ["PlayStation Portable (PSN) (Encrypted)"]),
	"Sony - PlayStation Vita (PSN) (Content)"                      : ("Advanced",     ["PlayStation Vita (PSN) (Content)"]),
	"Tiger - Game.com"                                             : ("Advanced",     ["Game.com"]),
	"Toshiba - Pasopia"                                            : ("Advanced",     ["Pasopia"]),
	"Toshiba - Visicom"                                            : ("Advanced",     ["Visicom"]),
	"VTech - CreatiVision"                                         : ("Advanced",     ["CreatiVision"]),
	"VTech - Mobigo"                                               : ("Advanced",     ["Mobigo"]),
	"VTech - V.Smile"                                              : ("Advanced",     ["V.Smile"]),
	"Watara - Supervision"                                         : ("Advanced",     ["supervision"]),
	"Yamaha - Copera"                                              : ("Advanced",     ["Copera"]),
	"Zeebo - Zeebo"                                                : ("Advanced",     ["Zeebo"]),
}
