# Each array includes alternate names for each system.
# You can add your own systems and/or alternate names.
# Capitalization doesn't matter, and each names is already checked with and without " - " where applicable (for example, "Nokia - N-Gage" covers both "Nokia - N-Gage" and "Nokia N-Gage")

systemNamesDict = {
	"Apple - I"                                                    : ["apple1"],
	"Apple - II"                                                   : ["apple2"],
	"Apple - II Plus"                                              : ["apple2plus"],
	"Apple - IIe"                                                  : ["apple2e"],
	"Apple - IIGS"                                                 : ["apple2gs"],
	"Apple - Macintosh"                                            : ["Macintosh"],
	"Atari - 2600"                                                 : ["atari2600", "Atari - Atari 2600", "a2600"],
	"Atari - 5200"                                                 : ["atari5200", "Atari - Atari 5200"],
	"Atari - 7800"                                                 : ["atari7800"],
	"Atari - 8-bit Family"                                         : ["atari800", "Atari - 800"],
	"Atari - Jaguar"                                               : ["Jaguar"],
	"Atari - Lynx"                                                 : ["lynx"],
	"Atari - ST"                                                   : ["atarist", "Atari - Atari ST"],
	"Atari - ST (Tapes)"                                           : ["Atari - Atari ST (Tapes)"],
	"Bandai - WonderSwan"                                          : ["wswan", "WonderSwan"],
	"Bandai - WonderSwan Color"                                    : ["wswanc", "WonderSwan Color"],
	"Coleco - ColecoVision"                                        : ["colecovision"],
	"Commodore - Amiga"                                            : ["Amiga"],
	"Commodore - Commodore 64"                                     : ["c64", "Commodore 64"],
	"Commodore - Commodore 64 (PP)"                                : ["Commodore 64 (PP)"],
	"Commodore - Commodore 64 (Tapes)"                             : ["Commodore 64 (Tapes)"],
	"Commodore - Plus-4"                                           : [],
	"Commodore - VIC-20"                                           : ["vic20", "VIC-20", "Commodore - VIC20"],
	"Mattel - Intellivision"                                       : ["intellivision"],
	"Microsoft - MSX"                                              : ["msx1", "MSX"],
	"Microsoft - MSX2"                                             : ["msx2"],
	"Mobile - J2ME"                                                : ["J2ME"],
	"NEC - PC Engine - TurboGrafx 16"                              : ["pcengine", "tg16", "PC Engine - TurboGrafx 16", "NEC - PC Engine", "PC Engine", "NEC - TurboGrafx 16", "TurboGrafx 16", "NEC - TurboGrafx16", "TurboGrafx16"],
	"NEC - PC Engine SuperGrafx"                                   : ["supergrafx", "PC Engine SuperGrafx"],
	"Nintendo - Family Computer Disk System"                       : ["fds", "Family Computer Disk System", "Nintendo - Famicom Disk System", "Famicom Disk System"],
	"Nintendo - Game & Watch"                                      : ["gw", "Nintendo - Game &amp; Watch", "Game &amp; Watch", "Game & Watch"],
	"Nintendo - Game Boy"                                          : ["gb", "Game Boy", "Gameboy"],
	"Nintendo - Game Boy Advance"                                  : ["gba", "Game Boy Advance", "Gameboy Advance", "Nintendo - Gameboy Advance"],
	"Nintendo - Game Boy Advance (Multiboot)"                      : ["Game Boy Advance (Multiboot)"],
	"Nintendo - Game Boy Color"                                    : ["gbc", "Game Boy Color", "Gameboy Color", "Nintendo - Gameboy Color"],
	"Nintendo - New Nintendo 3DS"                                  : ["New Nintendo 3DS", "New 3DS"],
	"Nintendo - New Nintendo 3DS (Digital)"                        : ["New Nintendo 3DS (Digital)"],
	"Nintendo - Nintendo 3DS"                                      : ["Nintendo 3DS", "3DS"],
	"Nintendo - Nintendo 3DS (Digital)"                            : ["Nintendo 3DS (Digital)", "3DS (Digital)"],
	"Nintendo - Nintendo 3DS (Digital) (CDN)"                      : ["Nintendo 3DS (Digital) (CDN", "3DS (Digital) (CDN"],
	"Nintendo - Nintendo 64"                                       : ["n64", "Nintendo 64"],
	"Nintendo - Nintendo 64DD"                                     : ["64dd", "Nintendo 64DD"],
	"Nintendo - Nintendo DS"                                       : ["ds", "nds", "Nintendo DS"],
	"Nintendo - Nintendo DS (Download Play)"                       : ["Nintendo DS (Download Play)"],
	"Nintendo - Nintendo DSi"                                      : ["Nintendo DSi", "DSi"],
	"Nintendo - Nintendo DSi (Digital)"                            : ["Nintendo DSi (Digital)"],
	"Nintendo - Nintendo DSi (Digital) (CDN)"                      : ["Nintendo DSi (Digital) (CDN)"],
	"Nintendo - Nintendo Entertainment System"                     : ["nes", "Nintendo Entertainment System", "Nintendo - Famicom", "Famicom"],
	"Nintendo - Pokemon Mini"                                      : ["pokemini", "Pokemon Mini"],
	"Nintendo - Satellaview"                                       : ["satellaview"],
	"Nintendo - Super Nintendo Entertainment System"               : ["snes", "Super Nintendo Entertainment System", "Super Nintendo", "Nintendo - Super Famicom", "Super Famicom"],
	"Nintendo - Virtual Boy"                                       : ["virtualboy", "Virtual Boy"],
	"Nintendo - Wii (Digital) (CDN)"                               : ["Wii (Digital) (CDN)"],
	"Nintendo - Wii U (Digital) (CDN)"                             : ["Wii U (Digital) (CDN)"],
	"Sega - 32X"                                                   : ["sega32x", "32X"],
	"Sega - Game Gear"                                             : ["gamegear", "Game Gear"],
	"Sega - Master System - Mark III"                              : ["mastersystem", "Master System - Mark III", "Sega - Master System", "Master System", "SMS"],
	"Sega - Mega Drive - Genesis"                                  : ["megadrive", "Sega Genesis", "Genesis", "Sega Mega Drive", "Mega Drive"],
	"Sega - SG-1000"                                               : ["sg1000", "SG-1000"],
	"Sinclair - ZX Spectrum +3"                                    : ["zxspectrum", "ZX Spectrum +3", "ZX Spectrum"],
	"SNK - Neo Geo Pocket"                                         : ["ngp", "Neo Geo Pocket"],
	"SNK - Neo Geo Pocket Color"                                   : ["ngpc", "Neo Geo Pocket Color"],
	"Sony - PlayStation Portable (PSN) (Encrypted)"                : ["PlayStation Portable (PSN) (Encrypted)"],

	"-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"                : [],
	"=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="                : [],

	"Acorn - Archimedes"                                           : ["Archimedes"],
	"Acorn - Atom"                                                 : ["Atom"],
	"Acorn - BBC Micro"                                            : ["bbcmicro", "BBC Micro"],
	"ACT - Apricot PC Xi"                                          : ["Apricot PC Xi"],
	"APF - Imagination Machine"                                    : ["Imagination Machine"],
	"APF - MP-1000"                                                : ["MP-1000"],
	"Bally - Astrocade"                                            : ["Astrocade"],
	"Bally - Astrocade (Tapes)"                                    : ["Astrocade (Tapes)"],
	"Bandai - Design Master Denshi Mangajuku"                      : ["Design Master Denshi Mangajuku"],
	"Bandai - Gundam RX-78"                                        : ["Gundam RX-78"],
	"Benesse - Pocket Challenge V2"                                : ["Pocket Challenge V2"],
	"Benesse - Pocket Challenge W"                                 : ["Pocket Challenge W"],
	"Bit Corporation - Gamate"                                     : ["Gamate"],
	"Casio - Loopy"                                                : ["Loopy"],
	"Casio - PV-1000"                                              : ["PV-1000"],
	"Emerson - Arcadia 2001"                                       : ["Arcadia 2001"],
	"Entex - Adventure Vision"                                     : ["Adventure Vision"],
	"Epoch - Game Pocket Computer"                                 : ["Game Pocket Computer"],
	"Epoch - Super Cassette Vision"                                : ["Super Cassette Vision"],
	"Fairchild - Channel F"                                        : ["channelf", "Channel F"],
	"Fukutake Publishing - StudyBox"                               : ["StudyBox"],
	"Funtech - Super Acan"                                         : ["Super Acan"],
	"GamePark - GP2X"                                              : ["GP2X"],
	"GamePark - GP2X (Digital)"                                    : ["GP2X (Digital)"],
	"GamePark - GP32"                                              : ["GP32"],
	"GCE - Vectrex"                                                : ["vectrex"],
	"Google - Android (Misc)"                                      : ["Android (Misc)"],
	"Hartung - Game Master"                                        : ["Game Master"],
	"IBM - PC and Compatibles"                                     : [],
	"IBM - PC and Compatibles (Digital) (Desura)"                  : [],
	"IBM - PC and Compatibles (Digital) (Misc)"                    : [],
	"IBM - PC and Compatibles (Digital) (Misc) (Adult)"            : [],
	"IBM - PC and Compatibles (Digital) (Unknown)"                 : [],
	"Interton - VC 4000"                                           : ["VC 4000"],
	"iQue - iQue"                                                  : ["iQue"],
	"Konami - Picno"                                               : ["Picno"],
	"LeapFrog - LeapPad"                                           : ["LeapPad"],
	"LeapFrog - Leapster Learning Game System"                     : ["Leapster Learning Game System"],
	"LeapFrog - My First LeapPad"                                  : ["My First LeapPad"],
	"Magnavox - Odyssey2"                                          : ["Odyssey2", "Magnavox - Odyssey 2"],
	"Microsoft - XBOX 360 (Digital)"                               : ["XBOX 360 (Digital)"],
	"Mobile - Palm OS"                                             : ["palm", "Palm OS"],
	"Mobile - Symbian"                                             : ["Symbian"],
	"Nichibutsu - My Vision"                                       : ["My Vision"],
	"Nintendo - amiibo"                                            : ["amiibo"],
	"Nintendo - e-Reader"                                          : ["e-Reader"],
	"Nintendo - Family Computer Network System"                    : ["Family Computer Network System"],
	"Nintendo - Kiosk Video Compact Flash"                         : ["Kiosk Video Compact Flash"],
	"Nintendo - Mario no Photopi SmartMedia"                       : ["Mario no Photopi SmartMedia"],
	"Nintendo - Misc"                                              : [],
	"Nintendo - Play-Yan"                                          : ["Play-Yan"],
	"Nintendo - Sufami Turbo"                                      : ["sufami", "Sufami Turbo"],
	"Nokia - N-Gage"                                               : ["N-Gage"],
	"Nokia - N-Gage 2.0"                                           : ["N-Gage 2.0"],
	"Ouya - Ouya"                                                  : ["Ouya"],
	"Philips - Videopac+"                                          : ["videopacplus", "Videopac+"],
	"RCA - Studio II"                                              : ["Studio II"],
	"Sega - Beena"                                                 : ["Beena"],
	"Sega - PICO"                                                  : ["PICO"],
	"Seta - Aleck64"                                               : ["Aleck64"],
	"Sony - PlayStation (PS one Classics) (PSN)"                   : ["PlayStation (PS one Classics) (PSN)"],
	"Sony - PlayStation 3 (PSN) (Content)"                         : ["PlayStation 3 (PSN) (Content)"],
	"Sony - PlayStation Mobile (PSN)"                              : ["PlayStation Mobile (PSN)"],
	"Sony - PlayStation Vita (PSN) (Content)"                      : ["PlayStation Vita (PSN) (Content)"],
	"Tiger - Game.com"                                             : ["Game.com"],
	"Toshiba - Pasopia"                                            : ["Pasopia"],
	"Toshiba - Visicom"                                            : ["Visicom"],
	"VTech - CreatiVision"                                         : ["CreatiVision"],
	"VTech - Mobigo"                                               : ["Mobigo"],
	"VTech - V.Smile"                                              : ["V.Smile"],
	"Watara - Supervision"                                         : ["supervision"],
	"Yamaha - Copera"                                              : ["Copera"],
	"Zeebo - Zeebo"                                                : ["Zeebo"],
}
